#!/bin/sh
### BEGIN INIT INFO
# Provides:          software-update
# Required-Start:    
# Required-Stop:     
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Software Update 
# Description:       Start Software Update signal.
### END INIT INFO

GPIO_PIN=12

case "$1" in
  start)
        echo $GPIO_PIN > /sys/class/gpio/export
        echo out > /sys/class/gpio/gpio$GPIO_PIN/direction
  ;;
  stop)
  ;;
esac

